reponote/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('report.urls')),
]

report/urls.py
from django.urls import path

from . import views


app_name = 'report'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
# リクエストされたURLが「blog-detal/レコードのid/」の場合は
    # BlogDetalを実行
    path(
        # 詳細ページのURLは「blog-detail/レコードのid/」
        'report-detail/<int:pk>/',
        # viewsモジュールのBlogDetailを実行
        views.ReportDetail.as_view(),
        # URLパターンの名前を'blog_detail'にする
        name='report_detail'
        ),
    # scienceカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「science-list/」
        'science-list/',
        # viewsモジュールのBlogDetailを実行
        views.ScienceView.as_view(),
        # URLパターンの名前を'science_list'にする
        name='science_list'
        ),
    # dailylifeカテゴリの一覧ページのURLパターン
    path(
        # dailylifeカテゴリの一覧ページのURLは「dailylife-list/」
        'dailylife-list/',
        # viewsモジュールのDailylifeViewを実行
        views.DailylifeView.as_view(),
        # URLパターンの名前を'dailylife_list'にする
        name='dailylife_list'
        ),
    # musicカテゴリの一覧ページのURLパターン
    path(
        # scienceカテゴリの一覧ページのURLは「music-list/」
        'music-list/',
        # viewsモジュールのMusicViewを実行
        views.MusicView.as_view(),
        # URLパターンの名前を'music_list'にする
        name='music_list'
        ),
    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        'contact/',
        # viewsモジュールのInquiryViewを実行
        views.ContactView.as_view(),
        # URLパターンの名前を'contact'にする
        name='contact'
        ),
]

report/models.py
from django.db import models


class ReportPost(models.Model):
    '''モデルクラス
    '''
    # カテゴリに設定する項目を入れ子のタプルとして定義
    # 最初の要素はモデルが使用する値、2番目の要素は選択メニューに表示する文字列
    CATEGORY = (('science', '科学のこと'), ('dailylife', '日常のこと'), ('music', '音楽のこと'))

    # タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル',  # フィールドのタイトル
        max_length=200  # 最大文字数は200
    )
    # 本文用のフィールド
    content = models.TextField(
        verbose_name='本文'  # フィールドのタイトル
    )
    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',  # フィールドのタイトル
        auto_now_add=True  # 日時を自動追加
    )
    # カテゴリのフィールド
    category = models.CharField(
        verbose_name='カテゴリ',  # フィールドのタイトル
        max_length=50,  # 最大文字数は50
        choices=CATEGORY
    )

    def __str__(self):
        '''オブジェクトを文字列に変換して返す

        Returns(str):投稿記事のタイトル
        '''
        return self.title

report/forms.py
# django.formsをインポート
from django import forms
# django.core.mailモジュールからEmailMessageをインポート
from django.core.mail import EmailMessage


class ContactForm(forms.Form):
    # フォームのフィールドをクラス変数として定義
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        '''ContactFormのコンストラクター

           フィールドの初期化を行う
        '''
        super().__init__(*args, **kwargs)
        # nameフィールドのplaceholderにメッセージを登録
        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください'
        # nameフィールドを出力する<input>タグのclass属性を設定
        self.fields['name'].widget.attrs['class'] = 'form-control'

        # emailフィールドのplaceholderにメッセージを登録
        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        # emailフィールドを出力する<input>タグのclass属性を設定
        self.fields['email'].widget.attrs['class'] = 'form-control'

        # titleフィールドのplaceholderにメッセージを登録
        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'
        # titleフィールドを出力する<input>タグのclass属性を設定
        self.fields['title'].widget.attrs['class'] = 'form-control'

        # messageフィールドのplaceholderにメッセージを登録
        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        # messageフィールドを出力する<input>タグのclass属性を設定
        self.fields['message'].widget.attrs['class'] = 'form-control'

    def send_email(self):
        '''フォームに入力された内容をメールで送信する

        '''
        # フォームに入力されたデータをフィールド名を指定して取得
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']
        # メールのタイトルの書式を設定
        subject = 'お問い合わせ: {}'.format(title)
        # フォームの入力データの書式を設定
        message = \
            '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\n{3}' \
                .format(name, email, title, message)
        # メールの送信元のアドレス
        from_email = 'denblog.pop@gmail.com'
        # 送信先のメールアドレス
        to_list = ['denblog.pop@gmail.com']
        # EmailMessageオブジェクトを生成
        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        # EmailMessageクラスのsend()でメールサーバーからメールを送信
        message.send()

report/views.py
from django.shortcuts import render
# django.views.genericからListView、DetailViewをインポート
from django.views.generic import ListView, DetailView
# モデルBlogPostをインポート
from .models import ReportPost
# django.views.genericからFormViewをインポート
from django.views.generic import FormView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからContactFormをインポート
from .forms import ContactForm
# django.contribからmesseagesをインポート
from django.contrib import messages


class IndexView(ListView):
    '''トップページのビュー

    投稿記事を一覧表示するのでListViewを継承する

    Attributes:
      template_name: レンダリングするテンプレート
      context_object_name: object_listキーの別名を設定
      queryset: データベースのクエリ
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # object_listキーの別名を設定
    context_object_name = 'orderby_records'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # BlogPostのレコードを投稿日時の降順で並べ替える
    queryset = ReportPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 4

class ReportDetail(DetailView):
    '''詳細ページのビュー

    投稿記事の詳細を表示するのでDetailViewを継承する
     Attributes:
      template_name: レンダリングするテンプレート
      Model: モデルのクラス
    '''
    # post.htmlをレンダリングする
    template_name = 'post.html'
    # クラス変数modelにモデルBlogPostを設定
    model = ReportPost


class ScienceView(ListView):
    '''科学(science)カテゴリの記事を一覧表示するビュー

    '''
    # science_list.htmlをレンダリングする
    template_name = 'science_list.html'
    # クラス変数modelにモデルBlogPostを設定
    model = ReportPost
    # object_listキーの別名を設定
    context_object_name = 'science_records'
    # category='science'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = ReportPost.objects.filter(
        category='science').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2


class DailylifeView(ListView):
    '''日常(dailylife)カテゴリの記事を一覧表示するビュー

    '''
    # dailylife_list.htmlをレンダリングする
    template_name = 'dailylife_list.html'
    # クラス変数modelにモデルBlogPostを設定
    model = ReportPost
    # object_listキーの別名を設定
    context_object_name = 'dailylife_records'
    # category='dailylife'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = ReportPost.objects.filter(
        category='dailylife').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2


class MusicView(ListView):
    '''音楽(music)カテゴリの記事を一覧表示するビュー

    '''
    # music_list.htmlをレンダリングする
    template_name = 'music_list.html'
    # クラス変数modelにモデルBlogPostを設定
    model = ReportPost
    # object_listキーの別名を設定
    context_object_name = 'music_records'
    # category='music'のレコードを抽出して
    # 投稿日時の降順で並べ替える
    queryset = ReportPost.objects.filter(
        category='music').order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 2


class ContactView(FormView):
    '''問い合わせページを一覧表示するビュー

    '''
    # contact.htmlをレンダリングする
    template_name = 'contact.html'
    # クラス変数form_classにforms.pyで定義したContactForを設定
    form_class = ContactForm
    # 送信完了後にリダイレクトするページ
    success_url = reverse_lazy('report:contact')

    def form_valid(self, form):
        '''FormViewクラスのform_valid()をオーバーライド

        フォームのバリデーションを通過したデータがPOSTされたときに呼ばれる
        メール送信を行う

        parameters:
          form(django.forms.Form):
            form_classに格納されているフォームのオブジェクト
        Return:
          HttpResponseRedirectのオブジェクト
          オブジェクトをインスタンスかするとsuccess_urlで
          設定されているURLにリダイレクトされる
        '''
        # foms.pyのsend_email()を実行してメール送信を行う
        form.send_email()
        # 送信完了後に表示するメッセージ
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

report/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする -->
{% load static %}
<!DOCTYPE html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <meta name="viewport"
        content="width=device-width,
                 initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <!-- ページタイトル -->
  <title>{% block title %}{% endblock %}</title>
  <!-- ページタイトル横に表示されるアイコン -->
  <!-- staticでfavicon.icoのURLを生成する -->
  <link href={% static 'assets/favicon.ico' %} rel="icon" type="image/x-icon"  />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js"
          crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
        rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
        rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <!-- staticでstyles.cssのURLを生成する -->
  <link href={% static 'css/styles.css' %} rel="stylesheet" />
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light"
       id="mainNav">
    <div class="container px-4 px-lg-5">
      <!--
      ナビゲーションバー左上のアンカーテキストとhref属性の値を変更
      -->
      <a class="navbar-brand"
         href={% url 'report:index' %}>Reponote</a>
      <button class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarResponsive"
              aria-controls="navbarResponsive"
              aria-expanded="false"
              aria-label="Toggle navigation">Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto py-4 py-lg-0">
          <li class="nav-item">
            <!--
            ナビゲーションメニューの「HOME」のhref属性の値を変更
            -->
            <a class="nav-link px-lg-3 py-3 py-lg-4"
               href="{% url 'report:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <!--
            ナビゲーションメニューの「SCIENCE」のリンク先を
            名前付きURLパターンscience_listに設定する
            -->
            <a class="nav-link px-lg-3 py-3 py-lg-4"
               href="{% url 'report:science_list' %}">SCIENCE</a>
          </li>
          <li class="nav-item">
            <!--
            ナビゲーションメニューの「DAILYLIFFE」のリンク先を
            名前付きURLパターンdailylife_listに設定する
            -->
            <a class="nav-link px-lg-3 py-3 py-lg-4"
               href="{% url 'report:dailylife_list' %}">DAILYLIFFE</a>
          </li>
          <li class="nav-item">
            <!--
            ナビゲーションメニューの「MUSIC」のリンク先を
            名前付きURLパターンmusic_listに設定する
            -->
            <a class="nav-link px-lg-3 py-3 py-lg-4"
               href="{% url 'report:music_list' %}">MUSIC</a>
          </li>
          <li class="nav-item">
            <!--
            ナビゲーションメニューの「CONTACT」のリンク先を
            名前付きURLパターンcontactに設定する
            -->
            <a class="nav-link px-lg-3 py-3 py-lg-4"
               href="{% url 'report:contact' %}">CONTACT</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <!-- ページのヘッダーはベーステンプレートを使用するページで設定する -->
  {% block header %}{% endblock %}

  <!-- Main Content -->
  <!-- ページのコンテンツはベーステンプレートを使用するページで設定する -->
  {% block contents %}{% endblock %}

  <!-- Footer -->
  <footer>
    <div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <!-- Twitterアイコンの<a>タグのhref属性にURLを設定 -->
              <a href="https://twitter.com/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <!--  Facebookアイコンの<a>タグのhref属性にURLを設定 -->
              <a href="https://www.facebook.com/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <!--  GitHubアイコンの<a>タグのhref属性にURLを設定 -->
              <a href="https://github.co.jp/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>

          <!-- 著作権の記載を独自のものに変更 -->
          <div class="small text-center text-muted fst-italic">
            Copyright &copy; reponote 2021</div>
        </div>
      </div>
    </div>
  </footer>


  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js">
  </script>

  <!-- Custom scripts for this template -->
  <!-- staticでjs/scripts.jsのURLを生成する -->
  <script src={% static 'js/scripts.js' %}></script>
</body>

</html>

report/templates/dailylife_list.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!--
 静的ファイルのURLを生成するstaticは
 個々のページで読み込むことが必要
 -->
{% load static %}
<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Reponote - Dailylife{% endblock %}

  <!-- Navigation -->
  <!-- ナビゲーションはベーステンプレートで設定済みなので削除 -->

  <!-- Page Header -->
  {% block header %}
  <!-- ページのヘッダーを設定(ドキュメントの構造に合わせてインデント) -->
  <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグに書き換え -->
  <header class="masthead"
          style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="site-heading">
            <!-- ヘッダーの大見出し(タイトル)を変更 -->
            <h1>Report</h1>
            <!-- サブタイトルを変更 -->
            <span class="subheading">Dailylifeカテゴリの記事一覧</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  {% endblock %}

  <!-- Main Content -->
  {% block contents %}
  <!-- ページのコンテンツを設定(ドキュメントの構造に合わせてインデント) -->
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!--
         レコードが格納されたdailylife_recordsから
         レコードを1行ずつrecordに取り出す
        -->
        {% for record in dailylife_records %}
        <div class="post-preview">
          <!--
          urlでURLパターン'report-detail/<int:pk>/'を生成し、
          詳細ページへのリンクを設定
          -->
          <a href="{% url 'report:report_detail' record.pk %}">
            <!-- 記事のタイトル -->
            <h2 class="post-title">
              <!-- titleフィールドを出力 -->
              {{record.title}}
            </h2>
            <!-- 投稿記事の本文 -->
            <h3 class="post-subtitle">
              <!-- サブタイトルの文字サイズを16ptにする -->
              <span style="font-size : 16pt">
                <!--
                 contentフィールドを出力
                 truncatecharsで出力する文字数を40以内に制限
                -->
                {{record.content|truncatechars:50}}
              </span>
            </h3>
          </a>
          <!-- 投稿日時とカテゴリ -->
          <p class="post-meta">
            <!-- ページの最上部にリンクする -->
            <a href="#">Reponote</a>
            <!-- posted_atフィールドを出力 -->
            {{record.posted_at}}に投稿／カテゴリ:
            <!-- categoryフィールドを出力-->
            {{record.category}}</p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}
        <!-- forによる繰り返しはここまで -->

        <!-- デフォルトで設定されている
        <div class="post-preview">～</div><hr>
        のブロック3個を削除
        -->

        <!-- Pager -->
        <!-- ページネーションの組み込み -->
        {% include "pagination.html" %}
      </div>
    </div>
  </div>
  <hr>
  {% endblock %}

  <!-- Footer -->
  <!-- フッター以下はベーステンプレートで設定済みなので削除 -->

report/templates/index.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!--
 静的ファイルのURLを生成するstaticは
 個々のページで読み込むことが必要
 -->
{% load static %}
<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Reponote{% endblock %}

  <!-- Navigation -->
  <!-- ナビゲーションはベーステンプレートで設定済みなので削除 -->

  <!-- Page Header -->
  {% block header %}
  <!-- ページのヘッダーを設定(ドキュメントの構造に合わせてインデント) -->
  <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグに書き換え -->
  <header class="masthead"
          style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="site-heading">
            <!-- ヘッダーの大見出し(タイトル)を変更 -->
            <h1>Reponote</h1>
            <!-- サブタイトルを変更 -->
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  {% endblock %}

  <!-- Main Content -->
  {% block contents %}
  <!-- ページのコンテンツを設定(ドキュメントの構造に合わせてインデント) -->
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!--
         レコードが格納されたorderby_recordsから
         レコードを1行ずつrecordに取り出す
        -->
        {% for record in orderby_records %}
        <div class="post-preview">
          <!--
          urlでURLパターン'report-detail/<int:pk>/'を生成し、
          詳細ページへのリンクを設定
          -->
          <a href="{% url 'report:report_detail' record.pk %}">
            <!-- 記事のタイトル -->
            <h2 class="post-title">
              <!-- titleフィールドを出力 -->
              {{record.title}}
            </h2>
            <!-- 投稿記事の本文 -->
            <h3 class="post-subtitle">
              <!-- サブタイトルの文字サイズを16ptにする -->
              <span style="font-size : 16pt">
                <!--
                 contentフィールドを出力
                 truncatecharsで出力する文字数を50以内に制限
                -->
                {{record.content|truncatechars:50}}
              </span>
            </h3>
          </a>
          <!-- 投稿日時とカテゴリ -->
          <p class="post-meta">
            <!-- ページの最上部にリンクする -->
            <a href="#">Reponote</a>
            <!-- posted_atフィールドを出力 -->
            {{record.posted_at}}に投稿／カテゴリ:
            <!-- categoryフィールドを出力-->
            {{record.category}}</p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}
        <!-- forによる繰り返しはここまで -->

        <!-- デフォルトで設定されている
        <div class="post-preview">～</div><hr>
        のブロック3個を削除
        -->

        <!-- Pager -->
        <!-- ページネーションの組み込み -->
        {% include "pagination.html" %}
      </div>
    </div>
  </div>
  <!-- Divider-->
  <hr class="my-4" />
  {% endblock %}

  <!-- Footer -->
  <!-- フッター以下はベーステンプレートで設定済みなので削除 -->

report/templates/music_list.html
<!DOCTYPE html>
<html lang="en">
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!--
 静的ファイルのURLを生成するstaticは
 個々のページで読み込むことが必要
 -->
{% load static %}
<!-- ヘッダー情報のページタイトルは
  ベーステンプレートを利用するページで設定する -->
{% block title %}Django's Blog - Music{% endblock %}

  <!-- Navigation -->
  <!-- ナビゲーションはベーステンプレートで設定済みなので削除 -->

  <!-- Page Header -->
  {% block header %}
  <!-- ページのヘッダーを設定(ドキュメントの構造に合わせてインデント) -->
  <!-- ヘッダーの背景イメージのリンク先url()の引数をstaticタグに書き換え -->
  <header class="masthead"
          style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
    <div class="container position-relative px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <div class="site-heading">
            <!-- ヘッダーの大見出し(タイトル)を変更 -->
            <h1>reponote</h1>
            <!-- サブタイトルを変更 -->
            <span class="subheading">Musicカテゴリの記事一覧</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  {% endblock %}

  <!-- Main Content -->
  {% block contents %}
  <!-- ページのコンテンツを設定(ドキュメントの構造に合わせてインデント) -->
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!--
         レコードが格納されたmusic_recordsから
         レコードを1行ずつrecordに取り出す
        -->
        {% for record in music_records %}
        <div class="post-preview">
          <!--
          urlでURLパターン'blog-detal/<int:pk>/'を生成し、
          詳細ページへのリンクを設定
          -->
          <a href="{% url 'report:report_detail' record.pk %}">
            <!-- 記事のタイトル -->
            <h2 class="post-title">
              <!-- titleフィールドを出力 -->
              {{record.title}}
            </h2>
            <!-- 投稿記事の本文 -->
            <h3 class="post-subtitle">
              <!-- サブタイトルの文字サイズを16ptにする -->
              <span style="font-size : 16pt">
                <!--
                 contentフィールドを出力
                 truncatecharsで出力する文字数を40以内に制限
                -->
                {{record.content|truncatechars:50}}
              </span>
            </h3>
          </a>
          <!-- 投稿日時とカテゴリ -->
          <p class="post-meta">
            <!-- ページの最上部にリンクする -->
            <a href="#">Reponote</a>
            <!-- posted_atフィールドを出力 -->
            {{record.posted_at}}に投稿／カテゴリ:
            <!-- categoryフィールドを出力-->
            {{record.category}}</p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
        {% endfor %}
        <!-- forによる繰り返しはここまで -->

        <!-- デフォルトで設定されている
        <div class="post-preview">～</div><hr>
        のブロック3個を削除
        -->

        <!-- Pager -->
        <!-- ページネーションの組み込み -->
        {% include "pagination.html" %}
      </div>
    </div>
  </div>
  <hr>
  {% endblock %}

  <!-- Footer -->
  <!-- フッター以下はベーステンプレートで設定済みなので削除 -->